site_name: Internship Report
docs_dir: learning-aws/docs

theme:
  name: material
  language: en
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy
palette:
    - scheme: default # Đưa default lên đầu tiên
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # Slate (tối) để xuống dưới
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:
      - Personal Information: index.md
      - Worklog:
          - Overview: worklog.md
          - Week 1: worklog/week1.md
          - Week 2: worklog/week2.md
  - More:
      - AWS Group Info: 'https://www.facebook.com/groups/awsstudygroupfcj/'




